name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    name: Testing
    steps:
    - uses: actions/checkout@v1
    - name: Download Composer cache dependencies from cache
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache Composer
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ hashFiles('**/composer.json') }}
        restore-keys: composer-
    - name: Install dependencies
      run: |
        composer install --no-interaction --no-interaction --prefer-source
      run: |
        phpunit --coverage-text --coverage-clover=coverage.xml
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
